### ISSUE TITLE
关于动画播放器的问题

### ISSUE THREAD

**Issue by yukikazenanodesu** [LinXueyuanStdio/AnimPlayer#1]
这个动画播放器我之前见到我我也在试过就是请问一下这个播放器里的cysp文件如何转成skel或者json文件在spine里面进行编辑和处理

**Comment by LinXueyuanStdio** [comment]
cysp可以拼接成skel（每个cysp是一个动画），但是暂时无法转化为json

**Comment by yukikazenanodesu** [comment]
那么有cysp拼成skel的例子吗？主要我也就是获取skel文件但是不知道如何拼成skel导入spine

**Comment by LinXueyuanStdio** [comment]
已经更新代码了。需要在加载模型后，点击下面的下载，可以下载到拼接好的skel。一个例子在另一个仓库里：https://github.com/LinXueyuanStdio/UEdbq

**Comment by yukikazenanodesu** [comment]
dalao这个有一个本地版的二进制拼合的工程吗？我这边也是拆了redive的包进行本地的skel文件的拼合再导入spine进行编辑.谢.

**Comment by LinXueyuanStdio** [comment]
我是直接在 js 里拼接，然后手动下载到本地。这里绕了一个弯，因为 js 不能直接保存到本地。
不过用 nodejs 应该是可以用脚本批量拼接的。你可以试试。
可以参考核心的拼接代码：

https://github.com/LinXueyuanStdio/AnimPlayer/blob/14ba41006ef90361b734c2d15596ad9ec77d925e/index.html#L522-L544

移植到 nodejs 要解决的东西主要是下拉选择框改为本地遍历了。可以直接搬 html 里的 js 代码，因为 nodejs 就是用 js 写脚本。。。
如果不想自己写的话，建议弄个自动化模拟点击，可以省很多时间。。。毕竟角色很多。。

本仓库以后可能会加 nodejs 版的吧。。但是最近没空。。

**Comment by LinXueyuanStdio** [comment]
我突然发现 cysp 也许是 Cygames Spine 的缩写哈哈哈哈

cysp 是 cy 自定义的格式，这样复用程度更高吧哈哈哈哈

怪不得现在 cysp 转 skel 的项目少哈哈

**Comment by yukikazenanodesu** [comment]
是的敢问dalao有一个qq吗还有一些问题这边qq给你说一下QAQ

**Comment by yukikazenanodesu** [comment]
其实cysp是spine导出的二进制自定义格式吧 cy其实吧角色的动作拆分成了很多cy格式的二进制进行复用

**Comment by LinXueyuanStdio** [comment]
我主页有邮箱，你发个邮件给我，我回复我QQ
