### ISSUE TITLE
Please include enemy character 可以添加除角色以外的嗎？

### ISSUE THREAD

**Issue by ghost** [LinXueyuanStdio/AnimPlayer#2]
user_id above 200000

**Comment by LinXueyuanStdio** [comment]
理论上spine可以加载任何角色。
至于公主连结Re:Dive的角色，取决于本仓库的数据来源： https://redive.estertion.win/spine/ 
如果是想自己魔改角色，可以导出到 spine 编辑器里自己改
以上，都和 user_id 关系不大。。。

**Comment by krulu** [comment]
哦
原來你這個也是調動estertion的數據庫
他的數據庫確實沒有user_id 200000以上的素材
