### ISSUE TITLE
能更新新的角色嗎？

### ISSUE THREAD

**Issue by psc2350** [LinXueyuanStdio/AnimPlayer#3]
能更新新的角色嗎？
另外角色的.cysp是怎麼合併的？

**Comment by LinXueyuanStdio** [comment]
已经更新到最新。

cysp分人物、骨架、技能、行动等模块，本质是 int array，按顺序拼合即可。具体细节自己看代码。

因为本项目不会和官方同步，所以自己使用时可以运行 `python run.py` 自动爬取到最新。

现在官方已经提供 skel 的下载了，本项目寿终正寝 ~
